# Generated by Django 5.2 on 2025-04-14 09:26

import django.db.models.deletion
import idea.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=idea.models.generate_lobby_code, max_length=10, unique=True)),
                ('host_name', models.CharField(max_length=100)),
                ('members', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host_code', models.TextField(blank=True, default='')),
                ('host_lang', models.CharField(default='python', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='idea.lobby')),
            ],
        ),
    ]
