# Generated by Django 5.2 on 2025-04-16 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0003_lobby_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='idea.lobby')),
            ],
        ),
    ]
