# Generated by Django 5.2 on 2025-04-16 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0004_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='code',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='participant',
            name='language',
            field=models.CharField(default='python', max_length=20),
        ),
        migrations.AddField(
            model_name='participant',
            name='output',
            field=models.TextField(blank=True, default=''),
        ),
    ]
