# Generated by Django 5.2 on 2025-04-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0005_participant_code_participant_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='host_output',
            field=models.TextField(blank=True, default=''),
        ),
    ]
